### PR TITLE
Add email loading state until user info resolved

### LINKED ISSUE #1059: Email settings hidden after refreshing a page
After logging in with persistent session, when user refresh a tab email settings disappear:
screenshot from 2014-11-03 16 27 47

### PR DESCRIPTION
**Pull request by deckar01**
Expose a function in session that returns a promise that resolves to the user private info.
Add a loading state and an error state to the email setting.

Fixes #1059.

### CODE REVIEW

**Comment by bartekn** [comment]
Pulled & tested :+1:

**Comment by thejollyrogers** [comment]
Here's an idea:
instead of creating new promise waitingForUserInfo and creating a new method (we already have a method getUser() in session), make User.load return a promise and store it in the session cache

**Comment by deckar01** [comment]
@thejollyrogers I agree that is how it should have been designed in the first place, but I don't want to change `getUser()`, because I would have to change all 108 usages which would significantly increase the surface area of this PR.

**Comment by thejollyrogers** [comment]
if we're taking the time to fix it now, shouldn't we take the time to do it right rather than moving forward with redundancy, different implementations, and confusion?

**Comment by deckar01** [comment]
@thejollyrogers This PR is to fix #1059, not refactor the way the entire app waits for user data. I will open a new issue.

**Comment by thejollyrogers** [comment]
Okay, thank you

**Pull request merged**
