### PR TITLE
Add utility for debugging user accounts

### PR DESCRIPTION
**Pull request by deckar01**
Adds a global javascript function for logging in and debugging the client with only a username or address.

`debugAs('jared')`

`debugAs('gEbULLfbgv1XHUgxq2C1FWLfKzDie2KWDG')`

### CODE REVIEW

**Comment by matschaffer** [comment]
I guess since we have a console warning in place we're probably okay though this feels like there could be some sort of vector for abuse/attack here.

**Comment by deckar01** [comment]
@matschaffer Since this function can only set the address, there is no potential to perform any actions. I can't think of an attack that can be performed by making a victim think they are logged into someone else's account. Besides that they would have to have at some point entered the command `debugAs('username')`, which print a message stating that you are debugging the client.

**Comment by matschaffer** [comment]
Thanks for the confirmation. Sounds reasonable in that case.

**Comment by thejollyrogers** [comment]
:+1:

**Pull request merged**
