### PR TITLE
Use ui sref

### LINKED ISSUE #1091: Back to dashboard button needs UI router attribute
The "Back to dashboard" button on the settings page is a relative URL instead of a hash URL, which causes the page to reload and logs users out if their session is not persistent.

### PR DESCRIPTION
**Pull request by deckar01**
Removed hard coded hrefs in favor of ui-sref.
Changed instances of `href=""` to `href="#"` for IE compatibility.

Fixes #1091.

### CODE REVIEW

**Comment by irisli** [comment]
screen shot 2015-01-09 at 11 47 36 am

The Manage Issuers & Gateways button doesn't work here anymore. In https://github.com/stellar/stellar-client/issues/1091#issuecomment-66210007, this was what made me think that `href` would be better since there currently isn't a way (as far as I know) of adding a GET param to `ui-sref` links.

**Comment by deckar01** [comment]
@irisli, you are right. I thought I tested it, but the link I used didn't actually have parameters.

http://stackoverflow.com/questions/25647454/how-to-pass-parameters-using-ui-sref-in-ui-router-to-controller

The accepted solution is a little more verbose and generic than we need, but contains some tricks we can use to get this working with `ui-sref`.

**Comment by deckar01** [comment]
@irisli I added a commit that uses `ng-click="gotoAddGateway()"` which sets the action to `add-gateway` and navigates to the dashboard.

**Comment by irisli** [comment]
Pulled and tested add gateway link. Maybe in the future with modular client, there would be a more unified way to do this, but as of now, this works fine. :+1:

**Pull request merged**
